title: "マインクラフト プログラミング会 まちをつくってみよう"
summary: "マインクラフト 教育版のMakeCodeを使って、まちを作っていく方法を小学生向けに説明します。"
topics: ["minecraft", "scratch"] # トピック（5つまで）
published: false # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - 00_axis
  - section_3 # 3章　だけど1
toc_depth: 3